name: hermez
description: Hermez native wallet project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.43+43



environment:
  sdk: ">=2.2.2 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  hermez_plugin:
    path: ../hermez_plugin/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  web3dart: ^1.2.3 # Update to 2.0.0 - problem with bitcoin_flutter
  http: ^0.12.0 # Update to 0.13.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  bip39: ^1.0.3 # update to 1.0.6
  #sacco: ^0.2.0
  # bch_wallet: ^0.0.3
  # dot_keygen: ^0.0.1
  #bitcoin_bip32: ^0.1.1
  # bitbox: ^0.0.5
  # wallet_core: ^0.2.4+23
  # wallet_hd: ^0.0.2
  # walletpackage: ^1.2.5
  bitcoin_flutter: ^2.0.2

  # tweetnacl: ^0.3.2
  pointycastle: ^1.0.1 # Update to 3.0.1 - dependency of web3dart 2.0.0
  hex: ^0.1.2 # Update to 0.2.0 - current version needed for bitcoin_flutter
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.5
  camera: ^0.5.7+3
  path_provider: ^1.1.0
  # share: ^2.0.1
  esys_flutter_share: ^1.0.2

  web_socket_channel: ^1.1.0
  intl: ^0.17.0
  # firebase_analytics: ^7.1.1
  # firebase_core: ^1.0.2
  # firebase_ml_vision: ^0.11.0
  url_launcher: ^6.0.3
  flutter_hooks: ^0.9.0
  built_value: ^8.0.0
  built_collection: ^5.0.0
  flutter_svg: ^0.22.0
  auto_size_text: ^2.1.0
  grouped_list: ^3.3.0
  local_auth: ^1.1.1
  flutter_windowmanager: ^0.0.2
  clipboard: ^0.1.3
  another_flushbar: ^1.10.20
  after_layout: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^8.0.4
  json_serializable: ^3.2.5
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Intro
    - intro_hermez_logo.png
    # Info
    - info.svg
    - info_success.png
    - info_failure.png
    - info_tx_failure.png
    - info_backup_success.png
    # Biometrics
    - biometrics_fingerprint.png
    - biometrics_face.png
    - face.png
    - fingerprint.png
    - backup_warning.png
    # Backup
    - info_backup.png
    # Remove account
    - remove_account_warning.png
    # Home
    - bt_move.svg
    - bt_receive.svg
    - bt_send.svg
    - tab_home.svg
    - tab_scan.svg
    - tab_settings.svg
    - move.png
    - hermez_logo.png
    - ethereum_logo.png
    - change_move_enable.svg
    - change_move_disable.svg
    - deposit3.png
    - hermez_logo_white.png
    - share.png
    - reload.svg
    # Account Details
    - tx_send.png
    - tx_receive.png
    # - tx_receive.svg
    - tx_move.png
    # - tx_move.svg
    # Settings
    - settings_currency_conversion.svg
    - settings_view_explorer.svg
    - settings_lock_wallet.svg
    - settings_show_recovery_phrase.svg
    - settings_change_passcode.svg
    - settings_face.svg
    - settings_fingerprint.svg
    - settings_force_withdrawal.svg
    - settings_default_fee.svg
    - settings_remove_account.svg
    # Scanner
    - switch_camera.svg
    - flash_on.png
    # - flash_on.svg
    - flash_off.svg

    # Amount
    - arrow_right.svg
    - arrow_down.svg
    - arrow_up.svg
    - deposit.png

    # Smart Contracts
    - ERC20ABI.json
    - HermezABI.json

    - account.png
    - wallet.png
    - search.png
    - label.png
    - list.png

    - add.png
    - warning.png
    - pending.png
    - upload.png
    - arrows_up_down.png
    - success.png
    - scan.svg
    - withdraw.png
    - withdraw2.png
    - show_explorer.png
    - paste.png
    - force_exit.png
    - qr_code.png
    - explorer.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: ModernEra
      fonts:
        - asset: fonts/ModernEra-Bold.ttf
        - asset: fonts/ModernEra-ExtraBold.ttf
        - asset: fonts/ModernEra-Medium.ttf
        - asset: fonts/ModernEra-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
